services:
  - type: worker
    name: filmsmax-bot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python botMovie.py
    envVars:
      - key: BOT_TOKEN
        sync: false
